name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: redis_demo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 3306 && echo "✅ MySQL is up" && break
            echo "⏳ Waiting for MySQL..."
            sleep 5
          done

      - name: Build the app
        run: ./mvnw clean install -DskipTests
        env:
          SPRING_DATA_REDIS_PORT: 6379
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/redis_demo
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      - name: Start Spring Boot app in background
        run: |
          nohup ./mvnw spring-boot:run -Dspring-boot.run.profiles=ci &
          sleep 20

      - name: Health check (actuator)
        run: curl -f http://localhost:8087/api/v1/actuator/health || (echo "❌ Actuator health check failed" && exit 1)

      - name: Verify Redis is running
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools
          redis-cli -h localhost ping
